name: 🛠️ Build application

on:
  push:
    branches:
      - '**' # matches every branch
      - '!main' # excludes master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm install

      - name: Build App
        run: npm run build
