name: 🚀 Deploy Umzug Meister

on:
  push:
    branches:
      - 'main'
jobs:
  build-deploy:
    if: "contains(github.event.head_commit.message, '[RELEASE]')"
    runs-on: ubuntu-latest
    environment:
      name: UM_PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm install

      - name: Add package version
        uses: jozsefsallai/node-package-version@v1.0.4

      - name: Build App
        run: npm run build
        env:
          REACT_APP_VERSION: ${{ env.PACKAGE_VERSION }}
          REACT_APP_WP_HOST: ${{ vars.REACT_APP_WP_HOST }}
          REACT_APP_DRIVE_ROOT_DIR: ${{ vars.REACT_APP_DRIVE_ROOT_DIR }}

      - name: Delete previous app
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          remoteFiles: 'main.*.js;'
          remoteDirectories: ${{ vars.REMOTE_DIR }}
          ignoreSSL: '1'

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          GITHUB_WORKSPACE: GITHUB_WORKSPACE
          FTP_SERVER: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASS }}
          LOCAL_DIR: ${{ github.workspace }}/build
          REMOTE_DIR: ${{ vars.REMOTE_DIR }}
          ARGS: --transfer-all

      - name: Delete index.html file
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          remoteFiles: '${{ vars.REMOTE_DIR }}/index.html'
          ignoreSSL: '1'
