name: Deploy Umzug Meister

on:
  push:
    branches:
      - 'main'
jobs:
  build-deploy:
    if: "contains(github.event.head_commit.message, '[RELEASE]')"
    runs-on: ubuntu-latest
    environment:
      name: UM_PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm install

      - uses: nyaa8/package-version@v1

      - name: Build App
        run: npm run build
        env:
          REACT_APP_VERSION: ${{ env.PACKAGE_VERSION }}
          REACT_APP_WP_HOST: ${{ vars.REACT_APP_WP_HOST }}

      - name: Remove files on FTP
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          remoteFiles: 'asset-manifest.json;main.*.js;static/js/*.*'
          remoteDirectories: '/http/wp-content/plugins/um-configurator/app-dist/rcAdmin1'
          ignoreSSL: '1'

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          GITHUB_WORKSPACE: GITHUB_WORKSPACE
          FTP_SERVER: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASS }}
          LOCAL_DIR: ${{ github.workspace }}/build
          REMOTE_DIR: /http/wp-content/plugins/um-configurator/app-dist/rcAdmin1
          ARGS: --transfer-all
