name: Semantic versioning

on:
  push:
    branches: ['main']

jobs:
  bump-version:
    name: 'Bump Version on default branch'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        with:
          patch-wording: 'fix,patch'
          minor-wording: 'new,feat,minor'
          major-wording: 'major'
