name: 🆙 Version Increment

on:
  push:
    branches:
      - '**'

jobs:
  version:
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      # - uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      # - run: git config --global user.name 'Action incrementer'
      # - run: git config --global user.email 'no@email.com'
      # - run: npm version patch -m "[RELEASE] %s"
      # - run: git push
