name: 🆙 Version Increment

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'RELEASE:')"
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          patch-wording: 'fix,deps'
          minor-wording: 'new,feat,minor'
          major-wording: 'major'
          commit-message: 'RELEASE: {{version}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
